"""empty message

Revision ID: 1c03679ef608
Revises: d9a624e9badd
Create Date: 2017-07-09 18:52:43.179229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c03679ef608'
down_revision = 'd9a624e9badd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'created_at')
    # ### end Alembic commands ###
